#!/bin/sh

DIR=$(dirname $0)
PERL5LIB="$DIR/mojo/lib"
export PERL5LIB
export TASKDEAL_SERVER_PORT=3000;
# For morbo starting bug
export MOJO_LISTEN=http://*:3001
exec $DIR/mojo/script/morbo $* $DIR/script/taskdeal-client
