#!/bin/env perl

use FindBin;
use lib "$FindBin::Bin/mojo/lib";
use Mojo::UserAgent;

my $command = shift;

my $app = Mojo::Server->load_app("$FindBin::Bin/script/envpush");
my $port = '3000';

my $ua = Mojo::UserAgent->new;

$ua->websocket("ws://localhost:$port/task" => sub {
  my ($ua, $tx) = @_;

  unless ($tx->is_websocket) {
    die "WebSocket handshake failed!";
    $tx->finish;
  }
        
  $tx->on(json => sub {
    my ($tx, $hash) = @_;
    
    $tx->finish;
  });
  
  $tx->send({json => {type => 'task', command => [$command]}});
});

Mojo::IOLoop->start unless Mojo::IOLoop->is_running;
