#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/extlib/lib/perl5";
use lib "$FindBin::Bin/mojo/lib";

use Config::Tiny;
use Mojo::Log;
use Mojo::UserAgent;

my $ua = Mojo::UserAgent
my $res = $ua->get('http://localhost:3000');
my $data = $res->json;
use Data::Dumper;
print Dumper $data;
