use Test::More 'no_plan';

use FindBin;
use lib "$FindBin::Bin/../mojo/lib";
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../extlib/lib/perl5";

use_ok('Taskdeal::Server');
use_ok('Taskdeal::Client');
use_ok('DBI');
use_ok('DBD::SQLite');
use_ok('Object::Simple');
use_ok('DBIx::Custom');
use_ok('Config::Tiny');
use_ok('Time::HiRes');
use_ok('Test::Simple');
use_ok('Validator::Custom');
use_ok('DBIx::Connector');
use_ok('Module::Build');
use_ok('Test::Harness');
use_ok('Module::Metadata');
use_ok('Perl::OSType');
use_ok('ExtUtils::CBuilder');
use_ok('File::Spec');
use_ok('IPC::Cmd');
use_ok('Locale::Maketext::Simple');
use_ok('Module::Load::Conditional');
use_ok('Module::Load');
use_ok('Params::Check');
use_ok('ExtUtils::ParseXS');
use_ok('Test::MockModule');
use_ok('Digest::SHA');
use_ok('Archive::Tar');
use_ok('Data::Page');
use_ok('Class::Accessor::Chained');
use_ok('Class::Accessor');
use_ok('Test::Exception');
use_ok('Sub::Uplevel');
